runtime: python39
env_variables:
  OPENAI_API_KEY: "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"
  YOUR_CHANNEL_ACCESS_TOKEN : "En1Q2i4+2InzJQKO1wJ+YIxIKoFOKC8VqcLvSkJjckuSmrj0dHrzh79c52OQCDKGJTXbDlgr0S7giPyej6fzCL2yFl+S1Eo8V5R//kM1fItLX4rGXUbvtusMlMNkGWy61mi9msxfkOT3JC020tH7gwdB04t89/1O/w1cDnyilFU="
  YOUR_CHANNEL_SECRET : "25d4b2851f882ea9619257e0e8dd7abf"